job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/axelayala1988/Jenkins.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven{
            goals('clean package')
            rootPOM('maven-samples/single-module/pom.xml')
            localRepository(LocalRepositoryLocation.LOCAL_TO_WORKSPACE))
        }
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
